server:
  port: 8002

spring:
  application:
    #注册到eureka微服务名称，若启动多个相同服务这个需要保存一致
    name: simple-consumer-ribbon-user

eureka:
  client:
    service-url:
      #注册到eureka服务端的地址
      defaultZone: http://root:123456@www.eureka9000.com:9000/eureka/,http://root:123456@www.eureka9001.com:9001/eureka/
  instance:
    #点击具体的微服务，右下角是否显示ip地址
    prefer-ip-address: true
    #显示微服务的名称
    instance-id: simple-consumer-ribbon-user-8002
