server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      #consul服务地址
      host: localhost
      #consul服务端口
      port: 8500
      discovery:
        service-name: ${spring.application.name}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.jolyoulu.springcloud.entities