server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #这里配置绑定RabbitMQ服务
        defaultRabbit: #定义一个名称，bindings配置中需要使用到
          type: rabbit #定义消息中间件类型
          environment: #设置rabbitmq的环境配置
            spring:
              rabbitmq:
                host: 192.168.100.101
                port: 5672
                username: admin
                password: 123
      bindings: #服务的整合
        input: #通道名称
          destination: studyExchange #表示该通道使用的交换机
          content-type: application/json #消息类型为json，文本则设为“text/plain”
          binder: defaultRabbit #绑定在binders中定义好的具体配置
          group: groupA

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2 #设置心跳的时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 5 #如果超过5秒间隔（默认90秒）
    instance-id: receive-8003.com #在信息列表中显示的主机名称
    prefer-ip-address: true #访问的路径变为ip地址