server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #远程库的配置文件
          uri: https://gitee.com/smallpage/springcloud-config.git
          #读取的目录
          search-paths:
            - springcloud-config
          #使用https协议需要账号密码
#          username:
#          password:
      #读取的分支
      label: master
  #配置rabbitmq连接地址与账号密码
  rabbitmq:
    host: 192.168.100.101
    port: 5672
    username: admin
    password: 123

management:
  #暴露bus刷新配置的端点
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
