server:
  port: 8401

spring:
  application:
    name: alibabacloud-sentinel-service
  cloud:
    nacos:
      discovery:
        #配置nacos的地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #假如端口被占用会自动从8719开始+1扫描，扫描到未被占用的端口
        port: 8719

#暴露服务，用于配置中心
management:
  endpoints:
    web:
      exposure:
        include: '*'