server:
  port: 9527

eureka:
  client:
    #表示需要将自己注册到注册中心上对外提供服务
    register-with-eureka: true
    #表示需要从注册中心抓取已经注册的服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway: #使用yml方式配置路由
      discovery:
        locator:
          enabled: true                       #开启从注册中心动态创建路由的功能，利用微服务名称进行理由
      routes:

        - id: payment_routh                   #路由ID，没有固定规则但是要求唯一，建议配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址(lb负载均衡://使用微服务名进行路由)
          predicates:
            - Path=/payment/get/**            #断言，路径相匹配的进行路由
            - Cookie=token,cloud\w*
            - Header=token,cloud\w*

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址(lb负载均衡://使用微服务名进行路由)
          predicates:
            - Path=/payment/create/**

