server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      #consul服务地址
      host: localhost
      #consul服务端口
      port: 8500
      discovery:
        service-name: ${spring.application.name}
